"""Renders the Analysis as an LE program (plan WA6 section "LE program")."""

from __future__ import annotations

from typing import Any

from .forms import FormProfile
from .model import Wording


def le_program(wording: Wording, element_analyses: list[dict[str, Any]], profile: FormProfile) -> str:
    used_form_ids = {analysis["formId"] for analysis in element_analyses if analysis.get("formId")}
    templates = [form.template + "." for form in profile.forms if form.form_id in used_form_ids]
    kb_name = wording.template_id.replace("-", "_")

    header = [
        f'% Logical English reading of "{wording.title}", revision {wording.revision}, '
        "generated by the word authoring POC.",
        f"% Profile {profile.profile_id} {profile.version}. Not checked by an LE parser.",
        "",
        "the templates are:",
        *(f"    {template}" for template in templates),
        "",
        f"the knowledge base {kb_name} includes:",
    ]

    blocks = [_block(analysis) for analysis in element_analyses]

    return "\n".join(header) + "\n\n" + "\n\n".join(blocks) + "\n"


def _block(analysis: dict[str, Any]) -> str:
    if analysis["basis"] == "none":
        return f'% {analysis["objectId"]} unmatched: {analysis["text"]}'
    basis_label = f'form {analysis["formId"]}' if analysis["basis"] == "form" else "keyword"
    return f'% {analysis["objectId"]} {analysis["relationClass"]} ({basis_label})\n{analysis["leSentence"]}'
