"""Re-serialises the instantiator's output with readable prefixes and a header."""
import sys
from rdflib import Graph
src, out = sys.argv[1], sys.argv[2]
g = Graph().parse(src)
L = "https://www.nebularis.org/neuro-semantic/lattice/"
for p, n in {"ins": "instrument#", "ins-voc": "instrument/vocab#", "bhv": "behaviour#", "elg": "eligibility#",
             "qnt": "quantification#", "pty": "party#"}.items():
    g.bind(p, L + n, replace=True)
g.bind("tmpl", "https://example.org/lattice/instrument/nonprofit-portfolio/form/")
g.bind("ex", "https://example.org/lattice/instrument/nonprofit-portfolio/")
head = """# GENERATED by tools/instrument_instantiator.py from nonprofit-portfolio.ttl for
# ex:policy-v1. Bound meaning is derived, never stored with the instance (D4).
# The instantiator reported nothing (instantiator-report.txt is empty).

"""
open(out, "w").write(head + g.serialize(format="turtle"))
print(len(g), "triples")
