# src/spc/ingress/rml_executor.py
"""
RML execution wrapper for ingress transformations.

Executes RML mappings (generated by the Mork-to-RML pipeline, which
already exists) against incoming data to produce RDF triples.

Supports two execution modes:
1. RMLMapper (Java): Full RML 1.0 support, invoked as subprocess
2. pyrml: Pure Python RML processor, limited but no Java dependency
"""

from __future__ import annotations
from pathlib import Path
import subprocess
import tempfile
from typing import Optional


class RMLExecutor:
    """Execute RML mappings to transform external data to RDF."""

    def __init__(self, rmlmapper_jar: Optional[str] = None):
        """
        Args:
            rmlmapper_jar: Path to rmlmapper.jar. If None, uses pyrml.
        """
        self.rmlmapper_jar = rmlmapper_jar

    def execute(
        self,
        mapping_path: Path,
        input_data: str,
        input_format: str = "json",
        output_format: str = "turtle",
    ) -> str:
        """
        Execute an RML mapping against input data.

        Args:
            mapping_path: Path to the RML mapping file (Turtle)
            input_data: The input data as a string (JSON, XML, CSV)
            input_format: Format of the input data
            output_format: Desired output format (turtle, ntriples, jsonld)

        Returns:
            The output RDF as a string in the specified format.
        """
        if self.rmlmapper_jar:
            return self._execute_java(
                mapping_path, input_data, input_format, output_format)
        else:
            return self._execute_pyrml(
                mapping_path, input_data, input_format, output_format)

    def execute_to_sparql_update(
        self,
        mapping_path: Path,
        input_data: str,
        input_format: str = "json",
        graph_name: Optional[str] = None,
    ) -> str:
        """
        Execute an RML mapping and return a SPARQL UPDATE INSERT DATA
        statement for materialising the results into Fuseki.
        """
        triples = self.execute(
            mapping_path, input_data, input_format, "ntriples")

        if graph_name:
            return f"INSERT DATA {{ GRAPH <{graph_name}> {{\n{triples}\n}} }}"
        else:
            return f"INSERT DATA {{\n{triples}\n}}"

    def _execute_java(
        self, mapping_path: Path, input_data: str,
        input_format: str, output_format: str,
    ) -> str:
        """Execute using rmlmapper.jar."""
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=f".{input_format}",
            delete=False
        ) as input_file:
            input_file.write(input_data)
            input_path = input_file.name

        with tempfile.NamedTemporaryFile(
            suffix=".ttl", delete=False
        ) as output_file:
            output_path = output_file.name

        try:
            format_flag = {
                "turtle": "turtle",
                "ntriples": "nquads",
                "jsonld": "jsonld",
            }.get(output_format, "turtle")

            cmd = [
                "java", "-jar", self.rmlmapper_jar,
                "-m", str(mapping_path),
                "-o", output_path,
                "-s", format_flag,
            ]

            proc = subprocess.run(
                cmd, capture_output=True, text=True, timeout=60)

            if proc.returncode != 0:
                raise RuntimeError(
                    f"RMLMapper failed: {proc.stderr}")

            with open(output_path) as f:
                return f.read()
        finally:
            Path(input_path).unlink(missing_ok=True)
            Path(output_path).unlink(missing_ok=True)

    def _execute_pyrml(
        self, mapping_path: Path, input_data: str,
        input_format: str, output_format: str,
    ) -> str:
        """Execute using pyrml (Python RML processor)."""
        try:
            from pyrml import RMLConverter

            converter = RMLConverter()
            # pyrml expects file paths; write input to temp
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=f".{input_format}",
                delete=False
            ) as f:
                f.write(input_data)
                input_path = f.name

            try:
                g = converter.convert(str(mapping_path))
                return g.serialize(format=output_format)
            finally:
                Path(input_path).unlink(missing_ok=True)

        except ImportError:
            raise RuntimeError(
                "Neither rmlmapper.jar nor pyrml available. "
                "Install pyrml or provide rmlmapper_jar path.")