// SPDX-License-Identifier: MPL-2.0
package org.nebularis.lattice.minting;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/** The library against the independently verified anchors and the vectors generated by the Python library. */
class ConformanceTest {

    static List<Path> vectorFiles() {
        return TestFiles.vectorFiles();
    }

    @Test
    void anchorsPass() throws IOException {
        Conformance.Report report = Conformance.verify(TestFiles.ANCHORS);
        assertEquals(List.of(), report.failures());
        assertTrue(report.passed() >= 70);
    }

    @Test
    void elevenGeneratedVectorFiles() {
        assertEquals(11, vectorFiles().size());
    }

    @ParameterizedTest
    @MethodSource("vectorFiles")
    void generatedVectorsPass(Path path) throws IOException {
        Conformance.Report report = Conformance.verify(path);
        assertEquals(List.of(), report.failures());
        assertTrue(report.passed() > 0);
    }

    @Test
    void aChangedTraceStepIsNamed() {
        Map<String, Object> doc = TestFiles.load(vectorFiles().stream()
                .filter(p -> p.getFileName().toString().startsWith("Product-")).findFirst().orElseThrow());
        Map<String, Object> vec = Values.map(Values.list(doc.get("positive")).get(0));
        List<?> trace = Values.list(vec.get("trace"));
        int tupleAt = 0;
        while (!"tuple".equals(Values.map(trace.get(tupleAt)).get("step"))) {
            tupleAt++;
        }
        Values.map(trace.get(tupleAt)).put("hex", "00");
        String expected = "step " + tupleAt + " (tuple)";
        assertTrue(Conformance.verify(doc).failures().stream().anyMatch(f -> f.contains(expected)));
    }

    @Test
    void cli(@TempDir Path tmp) throws IOException {
        PrintStream quiet = new PrintStream(new ByteArrayOutputStream(), true, StandardCharsets.UTF_8);
        String[] all = new String[vectorFiles().size() + 2];
        all[0] = "verify";
        all[1] = TestFiles.ANCHORS.toString();
        for (int i = 0; i < vectorFiles().size(); i++) {
            all[i + 2] = vectorFiles().get(i).toString();
        }
        assertEquals(0, Main.run(all, quiet, quiet));
        assertEquals(2, Main.run(new String[0], quiet, quiet));
        String text = Files.readString(vectorFiles().get(0));
        Path bad = tmp.resolve("bad.vectors.json");
        Files.writeString(bad, text.replaceFirst("\"iri\": \"", "\"iri\": \"x"));
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        assertEquals(1, Main.run(new String[] {"verify", bad.toString()}, new PrintStream(out, true, StandardCharsets.UTF_8), quiet));
        assertTrue(out.toString(StandardCharsets.UTF_8).contains("FAIL"));
    }
}
