# SPDX-License-Identifier: MPL-2.0
# NB: This module has been produced using GenAI

"""Command line for the persistence compiler.

``compile``
    Load ontology/persistence graphs plus an adopter's applied ontology,
    resolve every target, validate, select operations, and emit a
    ``dal:CompiledProfile`` graph (Turtle). Never produces SPARQL text and
    never touches a live backend (ADR-A79).

``instantiate``
    Read a compiled profile and the checked-in template library, and
    write one ``.rq`` file per generated operation. Entirely optional.

``export-recipes``
    Read a compiled profile and write one JSON minting recipe per
    ``dal:MintingRecipe`` (identity-minting-specification.md), and with
    ``--vectors`` a conformance vectors file per recipe, generated by the
    Python minting library (packages/minting/python).

``hygiene``
    Run the static hygiene checks (formal-methods track H, slice H1) over a
    configuration. Exits 1 on any violation, 0 otherwise (warnings are
    printed but do not fail).

``witness``
    Check that every refusal, warning, SHACL shape and audit query has a
    fixture that triggers it, or is listed as a known gap (slice H1.2).
    Exits 1 on an unlisted gap, a stale gap or a misbehaving audit witness.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from rdflib import Graph

from .capability import load_capability_spec
from .compiler import CompileError, compile_to_graph
from .hygiene import VIOLATION, check_prefix_antichain
from .witness import check_witness_coverage
from .instantiate import instantiate_to_directory
from .namespaces import DAL
from .recipes import export_recipes


def _load_graph(config_paths: list[str], capability_spec: str | None) -> Graph:
    graph = Graph()
    graph.bind("dal", DAL)
    for path in config_paths:
        p = Path(path)
        if p.is_dir():
            for ttl_file in sorted(p.glob("*.ttl")):
                graph.parse(ttl_file, format="turtle")
        else:
            graph.parse(p, format="turtle")
    if capability_spec:
        graph.parse(capability_spec, format="turtle")
    return graph


def cmd_compile(args: argparse.Namespace) -> int:
    graph = _load_graph(args.config, args.capability_spec)
    try:
        out, compiled = compile_to_graph(graph, fail_on_capability_mismatch=not args.no_fail_on_capability)
    except CompileError as e:
        print(f"compile failed: {e}", file=sys.stderr)
        return 1

    if not compiled:
        print("no targets discovered (no dal:targetClass found; pass --target-class explicitly?)", file=sys.stderr)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out.serialize(destination=str(out_path), format="turtle")
    print(f"compiled {len(compiled)} target(s) -> {out_path}", file=sys.stderr)
    return 0


def cmd_instantiate(args: argparse.Namespace) -> int:
    profile = Graph()
    profile.parse(args.compiled_profile, format="turtle")
    template_dir = Path(args.template_dir) if args.template_dir else None
    written = instantiate_to_directory(profile, Path(args.out), template_dir)
    for path in written:
        print(f"wrote {path}", file=sys.stderr)
    return 0


def cmd_export_recipes(args: argparse.Namespace) -> int:
    profile = Graph()
    profile.parse(args.compiled_profile, format="turtle")
    written = export_recipes(profile, Path(args.out), vectors=args.vectors)
    for path in written:
        print(f"wrote {path}", file=sys.stderr)
    if not written:
        print("no dal:MintingRecipe in the compiled profile", file=sys.stderr)
    return 0


def cmd_hygiene(args: argparse.Namespace) -> int:
    graph = _load_graph(args.config, None)
    findings = check_prefix_antichain(graph)
    for finding in findings:
        print(finding)
    violations = sum(1 for f in findings if f.severity == VIOLATION)
    print(f"hygiene: {violations} violation(s), {len(findings) - violations} warning(s)", file=sys.stderr)
    return 1 if violations else 0


def cmd_witness(args: argparse.Namespace) -> int:
    report = check_witness_coverage()
    for line in report.lines(verbose=args.verbose):
        print(line)
    return 0 if report.ok else 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="persistence")
    sub = parser.add_subparsers(dest="command", required=True)

    p_compile = sub.add_parser("compile", help="resolve and validate a configuration, emit a dal:CompiledProfile")
    p_compile.add_argument("config", nargs="+", help="ontology/persistence graph file(s) or directory(ies)")
    p_compile.add_argument("--capability-spec", help="an optional dal:CapabilitySpec Turtle file")
    p_compile.add_argument("--out", required=True, help="output path for the compiled profile (Turtle)")
    p_compile.add_argument(
        "--no-fail-on-capability",
        action="store_true",
        help="do not fail the compile when a supplied CapabilitySpec's check fails (report only)",
    )
    p_compile.set_defaults(func=cmd_compile)

    p_instantiate = sub.add_parser("instantiate", help="render a compiled profile's operations to SPARQL text")
    p_instantiate.add_argument("compiled_profile", help="a dal:CompiledProfile Turtle file")
    p_instantiate.add_argument("--template-dir", help="override the built-in template library directory")
    p_instantiate.add_argument("--out", required=True, help="output directory for generated .rq files")
    p_instantiate.set_defaults(func=cmd_instantiate)

    p_export = sub.add_parser("export-recipes", help="write each dal:MintingRecipe in a compiled profile as a JSON recipe")
    p_export.add_argument("compiled_profile", help="a dal:CompiledProfile Turtle file")
    p_export.add_argument("--out", required=True, help="output directory for the .recipe.json files")
    p_export.add_argument("--vectors", action="store_true",
                          help="also write a .vectors.json conformance file per recipe (needs packages/minting/python)")
    p_export.set_defaults(func=cmd_export_recipes)

    p_hygiene = sub.add_parser("hygiene", help="run the static hygiene checks over a configuration")
    p_hygiene.add_argument("config", nargs="+", help="ontology/persistence graph file(s) or directory(ies)")
    p_hygiene.set_defaults(func=cmd_hygiene)

    p_witness = sub.add_parser("witness", help="check that every rule, shape and audit has a fixture that triggers it")
    p_witness.add_argument("--verbose", action="store_true", help="also list each witnessed rule and each known gap")
    p_witness.set_defaults(func=cmd_witness)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


__all__ = ["main", "build_parser"]
