# SPDX-License-Identifier: MPL-2.0
"""Ontology release register (ADR-A86 second addendum,
docs/architecture/ontology-versioning-policy.md).

Every version of every ontology document under a ``spec/`` or ``vocab/``
directory, and of every layer's ``shapes/`` and ``projection/`` directory
(versioned by its ``.version`` file), is released by a git tag,
``<name>-vX.Y.Z``, and listed in ``docs/architecture/ontology-releases.md``
with links to its raw content at that tag. Rows are never edited once written.

``write`` adds a row for each current version not yet listed. ``check`` fails
when a current version has no row, or when its tag exists but names a commit
where the document has a different version. Both list the tags that still
have to be created, which only a person does, after committing.

Usage::

    python tools/ontology_releases.py write|check [--root .]
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ontology_version_check import (  # noqa: E402
    ROOT,
    VERSION_FILE,
    artefact_directories,
    artefact_files,
    artefact_version,
    extract_version_iris,
    find_in_scope_ttl_files,
    git_lines,
    git_show,
    requires_version_iri,
)

REGISTER = Path("docs/architecture/ontology-releases.md")
RAW = "https://raw.githubusercontent.com/nebularis/lattice/refs/tags"
ROW_RE = re.compile(r"^\| ([a-z0-9-]+) \| (\d+\.\d+\.\d+) \|")
NAME_PREFIXES = (("neuro-semantic", "lattice"), ("neuro-semantic",), ("ontologies",))
HEADER = """---
layout: architecture
title: Ontology Releases
eyebrow: Every released version, fetchable by tag
dek: "Each version of each LATTICE ontology document is released by a git tag. Its content, and its layer's shapes and projections, can be fetched at that tag."
description: "Register of released LATTICE ontology versions, with raw links to each document and its artefacts at the version's git tag."
note: "Generated by tools/ontology_releases.py. Rows are added, never edited. See the ontology versioning policy."
---

<!-- SPDX-License-Identifier: CC-BY-SA-4.0 -->

Version IRIs do not dereference yet. Until they do, a released version is fetched from
GitHub at its tag, named after the release and its version (foundation-v0.3.0), following
the [ontology versioning policy](ontology-versioning-policy.md#releasing-a-version). A layer's
shapes and projections are released on their own, versioned by the .version file in their
directory, and have no version IRI.

Click a file to download it under the name shown. Opening it in a new tab shows the raw
content at the tag.

<script>
// raw.githubusercontent.com allows cross-origin reads but serves text/plain, and browsers
// ignore the download attribute across origins, so fetch the file and save it locally.
document.addEventListener("click", async (event) => {
  const link = event.target.closest('a[href^="https://raw.githubusercontent.com/"]');
  if (!link || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
  event.preventDefault();
  const response = await fetch(link.href);
  if (!response.ok) { window.location.href = link.href; return; }
  const url = URL.createObjectURL(new Blob([await response.text()], { type: "text/turtle" }));
  const save = Object.assign(document.createElement("a"), { href: url, download: link.textContent });
  document.body.append(save);
  save.click();
  save.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
});
</script>

| Name | Version | Tag | Version IRI | Files |
|---|---|---|---|---|
"""


def release_name(version_iri: str) -> tuple[str, str]:
    """``(name, version)`` from a version IRI: the path without its version,
    known namespace prefixes dropped, segments joined by ``-``, lower case."""
    *segments, version = urlparse(version_iri).path.strip("/").split("/")
    for prefix in NAME_PREFIXES:
        if tuple(segments[: len(prefix)]) == prefix:
            segments = segments[len(prefix):]
            break
    return "-".join(segments).lower(), version


def releases(root: Path) -> list[dict]:
    """The current version of every released document and artefact
    directory, with its files. ``marker`` is the file whose content at the
    tag must hold ``marker_text``."""
    found = []
    for path in find_in_scope_ttl_files(root):
        relative = path.relative_to(root).as_posix()
        if not requires_version_iri(Path(relative)):
            continue
        for version_iri in sorted(extract_version_iris(path.read_text(encoding="utf-8"))):
            name, version = release_name(version_iri)
            found.append({"name": name, "version": version, "iri": version_iri, "marker": relative,
                          "marker_text": version_iri, "tag": f"{name}-v{version}", "files": [relative]})
    for directory in artefact_directories(root):
        name = "-".join(Path(directory).parts[1:]).lower()
        version = artefact_version(root, directory) or ""
        found.append({"name": name, "version": version, "iri": None, "marker": f"{directory}/{VERSION_FILE}",
                      "marker_text": version, "tag": f"{name}-v{version}", "files": artefact_files(root, directory)})
    return found


def label(release: dict, path: str) -> str:
    """A file's download name: ``persistence-spec-v0.2.1.ttl``,
    ``foundation-vocab-v0.3.0.ttl``, ``persistence-shapes-constraints-v0.1.0.ttl``."""
    file = Path(path)
    if release["iri"] is None:
        return f"{release['name']}-{file.stem.lower()}-v{release['version']}{file.suffix}"
    kind = "" if release["name"].endswith("-vocab") else "-spec"
    return f"{release['name']}{kind}-v{release['version']}{file.suffix}"


def row(release: dict) -> str:
    links = " · ".join(f"[{label(release, path)}]({RAW}/{release['tag']}/{path})" for path in release["files"])
    iri = f"<{release['iri']}>" if release["iri"] else "none"
    return f"| {release['name']} | {release['version']} | {release['tag']} | {iri} | {links} |"


def listed(root: Path) -> dict[tuple[str, str], str]:
    path = root / REGISTER
    if not path.exists():
        return {}
    return {match.groups(): line for line in path.read_text(encoding="utf-8").splitlines()
            if (match := ROW_RE.match(line))}


def version_key(key: tuple[str, str]) -> tuple:
    return key[0], tuple(int(part) if part.isdigit() else part for part in key[1].split("."))


def write(root: Path) -> list[str]:
    """Add rows for unlisted current versions. Returns the tags added."""
    rows = listed(root)
    added = []
    for release in releases(root):
        key = (release["name"], release["version"])
        if key not in rows:
            rows[key] = row(release)
            added.append(release["tag"])
    (root / REGISTER).parent.mkdir(parents=True, exist_ok=True)
    (root / REGISTER).write_text(HEADER + "\n".join(rows[key] for key in sorted(rows, key=version_key)) + "\n", encoding="utf-8")
    return added


def check(root: Path) -> list[str]:
    rows = listed(root)
    tags = set(git_lines(root, "tag", "--list"))
    problems = []
    for release in releases(root):
        if (release["name"], release["version"]) not in rows:
            problems.append(f"{release['marker']}: {release['tag']} has no row in {REGISTER}, run: mise run build:ontology-releases")
        elif release["tag"] in tags and release["marker_text"] not in (git_show(root, release["tag"], release["marker"]) or ""):
            problems.append(f"tag {release['tag']} names a commit where {release['marker']} does not hold {release['marker_text']}")
    return problems


def pending_tags(root: Path) -> list[str]:
    tags = set(git_lines(root, "tag", "--list"))
    return [f"{name}-v{version}" for name, version in sorted(listed(root), key=version_key)
            if f"{name}-v{version}" not in tags]


def notice(tags: list[str]) -> str:
    red, reset = ("\033[1;31m", "\033[0m") if sys.stdout.isatty() else ("", "")
    bar = "!" * 72
    lines = [bar, "ACTION REQUIRED: create these release tags on the commit that adds their rows,",
             "then push them. Only a person creates tags.", ""]
    lines += [f"  {chr(97 + i) if i < 26 else i + 1}. {tag}" for i, tag in enumerate(tags)]
    lines += ["", "  git tag " + " && git tag ".join(tags), "  git push origin " + " ".join(tags), bar]
    return red + "\n".join(lines) + reset


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("command", choices=["write", "check"])
    parser.add_argument("--root", default=str(ROOT))
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    if args.command == "write":
        added = write(root)
        print(f"{REGISTER}: {len(added)} release row(s) added")
        problems = []
    else:
        problems = check(root)
        for problem in problems:
            print(f"UNRELEASED {problem}", file=sys.stderr)
        if not problems:
            print(f"{REGISTER}: every current ontology version is listed")
    tags = pending_tags(root)
    if tags:
        print(notice(tags))
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
