# SPDX-License-Identifier: MPL-2.0
"""Ontology import resolution for consumers (ADR-A88).

Generates ``ontology/catalog-v001.xml``, an OASIS XML catalog mapping every
ontology IRI and ``owl:versionIRI`` declared under ``ontology/`` to its file by
a path relative to the catalog, plus a stub catalog in every ``spec/`` and
``vocab/`` directory whose only entry is a ``nextCatalog`` pointing at the root
catalog (Protégé reads the catalog beside the document it opens).

Usage::

    python tools/ontology_catalog.py write            # regenerate every catalog
    python tools/ontology_catalog.py check            # drift, resolution, known defects
    python tools/ontology_catalog.py closure <iri> [--catalog <path>]

``closure`` loads a document's import closure into one ``rdflib`` graph
through a catalog, following ``nextCatalog`` chains, so a consumer that chains
its own catalog to this one can load LATTICE with no further configuration.
Only ``uri`` and ``nextCatalog`` entries are interpreted. ``xml:base`` is not.
"""

from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional
from xml.sax.saxutils import quoteattr

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ontology_version_check import ONTOLOGY_MARKER_RE, repository_files, requires_version_iri  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
ONTOLOGY_ROOT = "ontology"
CATALOG_NAME = "catalog-v001.xml"
CATALOG_NS = "urn:oasis:names:tc:entity:xmlns:xml:catalog"

# Imports of ontologies held outside this repository, with the location a
# catalog-aware tool should load them from. The check accepts these without
# fetching them.
EXTERNAL: dict[str, str] = {
    "http://w3id.org/rml": "http://w3id.org/rml",
    "http://www.w3.org/2003/11/swrl": "https://www.w3.org/Submission/SWRL/swrl.owl",
    "http://www.w3.org/2004/02/skos/core": "https://www.w3.org/2009/08/skos-reference/skos.rdf",
    "http://www.w3.org/ns/prov-o-20130430": "https://www.w3.org/ns/prov-o-20130430",
    "http://www.w3.org/ns/shacl": "https://www.w3.org/ns/shacl.ttl",
}

# Pre-existing defects the check reports without failing. Remove an entry in
# the change that fixes it. The check fails on an entry whose file no longer
# has a problem, so this list only shrinks.
_MORK_FRAGMENT = "imports http://www.nebularis.org/ontologies/Mork# (stray fragment) instead of the Mork ontology IRI"
KNOWN_DEFECTS: dict[str, str] = {
    "ontology/mork/examples/Governance/GovernanceAndVersioning.ttl": _MORK_FRAGMENT,
    "ontology/mork/examples/Zoo/PropertyGeneration.ttl": _MORK_FRAGMENT,
}

GENERATED_NOTE = "<!-- Generated by tools/ontology_catalog.py (ADR-A88). Do not edit by hand. -->"
XML_HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n<!-- SPDX-License-Identifier: MPL-2.0 -->\n' + GENERATED_NOTE + "\n"


class CatalogError(Exception):
    """The tree cannot be catalogued, or an IRI cannot be resolved."""


@dataclass
class Document:
    path: str  # repository-relative, POSIX
    names: list[str] = field(default_factory=list)  # ontology IRI, then version IRIs
    imports: list[str] = field(default_factory=list)


@dataclass
class Scan:
    documents: list[Document]
    unparseable: dict[str, str]

    def declared(self) -> dict[str, str]:
        """IRI -> repository-relative path. Raises on an IRI declared twice."""
        owners: dict[str, str] = {}
        for document in self.documents:
            for name in document.names:
                if name in owners and owners[name] != document.path:
                    raise CatalogError(f"{name} is declared by both {owners[name]} and {document.path}")
                owners[name] = document.path
        return owners


def ontology_files(root: Path) -> list[Path]:
    """Ontology documents git tracks or would track. Ignored build output is
    excluded, so the committed catalog does not depend on one machine's builds."""
    return [
        path
        for path in repository_files(root, ".ttl")
        if ONTOLOGY_MARKER_RE.search(path.read_text(encoding="utf-8", errors="ignore"))
    ]


def scan(root: Path) -> Scan:
    documents: list[Document] = []
    unparseable: dict[str, str] = {}
    for path in ontology_files(root):
        relative = path.relative_to(root).as_posix()
        try:
            graph = Graph().parse(path, format="turtle")
        except Exception as error:  # rdflib raises several unrelated types
            unparseable[relative] = str(error).splitlines()[0]
            continue
        for node in sorted(graph.subjects(RDF.type, OWL.Ontology)):
            if not isinstance(node, URIRef):
                continue
            documents.append(
                Document(
                    path=relative,
                    names=[str(node)] + sorted(str(v) for v in graph.objects(node, OWL.versionIRI)),
                    imports=sorted(str(i) for i in graph.objects(node, OWL.imports)),
                )
            )
    return Scan(documents, unparseable)


# -- generation --------------------------------------------------------------


def _catalog(lines: Iterable[str]) -> str:
    body = "".join(f"    {line}\n" for line in lines)
    return f'{XML_HEADER}<catalog xmlns="{CATALOG_NS}" prefer="public">\n{body}</catalog>\n'


def render_root(result: Scan) -> str:
    declared = result.declared()
    lines = [
        f"<uri name={quoteattr(name)} uri={quoteattr(Path(path).relative_to(ONTOLOGY_ROOT).as_posix())}/>"
        for name, path in sorted(declared.items())
    ]
    lines.append("<!-- External imports, not held in this repository -->")
    lines += [f"<uri name={quoteattr(name)} uri={quoteattr(location)}/>" for name, location in sorted(EXTERNAL.items())]
    return _catalog(lines)


def render_stub(directory: Path) -> str:
    target = os.path.relpath(Path(ONTOLOGY_ROOT) / CATALOG_NAME, directory)
    return _catalog([f"<nextCatalog catalog={quoteattr(Path(target).as_posix())}/>"])


def stub_directories(root: Path) -> list[Path]:
    """Repository-relative directories holding a published ontology document."""
    directories = {
        path.parent.relative_to(root)
        for path in ontology_files(root)
        if requires_version_iri(path.relative_to(root))
    }
    return sorted(directories)


def expected_files(root: Path, result: Optional[Scan] = None) -> dict[str, str]:
    result = result or scan(root)
    files = {f"{ONTOLOGY_ROOT}/{CATALOG_NAME}": render_root(result)}
    for directory in stub_directories(root):
        files[(directory / CATALOG_NAME).as_posix()] = render_stub(directory)
    return files


def write(root: Path) -> list[str]:
    written = []
    for relative, text in expected_files(root).items():
        path = root / relative
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            written.append(relative)
    return written


# -- checking ----------------------------------------------------------------


def _catalog_entries(path: Path) -> list[tuple[str, str]]:
    tree = ET.parse(path)
    return [(uri.get("name", ""), uri.get("uri", "")) for uri in tree.getroot().iter(f"{{{CATALOG_NS}}}uri")]


def check(root: Path) -> tuple[list[str], list[str]]:
    """(problems, known) for the tree at ``root``. Problems fail the check.
    Known lists defects from ``KNOWN_DEFECTS`` that are still present."""
    result = scan(root)
    declared = result.declared()
    by_file: dict[str, list[str]] = {}

    def report(path: str, message: str) -> None:
        by_file.setdefault(path, []).append(message)

    for path, error in result.unparseable.items():
        report(path, f"does not parse: {error}")
    for document in result.documents:
        for target in document.imports:
            if target not in declared and target not in EXTERNAL:
                report(document.path, f"imports {target}, which no document under {ONTOLOGY_ROOT}/ declares")

    expected = expected_files(root, result)
    for relative, text in expected.items():
        path = root / relative
        if not path.exists():
            report(relative, "missing, run: python tools/ontology_catalog.py write")
        elif path.read_text(encoding="utf-8") != text:
            report(relative, "differs from a fresh generation, run: python tools/ontology_catalog.py write")
    for path in repository_files(root, "/" + CATALOG_NAME):
        relative = path.relative_to(root).as_posix()
        if relative not in expected:
            report(relative, "is not a generated catalog, remove it or regenerate")

    catalog = root / ONTOLOGY_ROOT / CATALOG_NAME
    if catalog.exists():
        for name, location in _catalog_entries(catalog):
            if name in EXTERNAL:
                continue
            target = f"{ONTOLOGY_ROOT}/{location}"
            if declared.get(name) != target:
                report(f"{ONTOLOGY_ROOT}/{CATALOG_NAME}", f"maps {name} to {location}, which does not declare it")

    problems: list[str] = []
    known: list[str] = []
    for path, messages in sorted(by_file.items()):
        target = known if path in KNOWN_DEFECTS else problems
        target += [f"{path}: {message}" for message in messages]
    for path, reason in sorted(KNOWN_DEFECTS.items()):
        if path not in by_file:
            problems.append(f"{path}: listed in KNOWN_DEFECTS ({reason}) but no longer defective, remove the entry")
    return problems, known


# -- resolution --------------------------------------------------------------


class Catalog:
    """An OASIS XML catalog with its ``nextCatalog`` chain."""

    def __init__(self, path: Path, _seen: Optional[set[Path]] = None) -> None:
        self.path = path.resolve()
        seen = _seen if _seen is not None else set()
        seen.add(self.path)
        root = ET.parse(self.path).getroot()
        self.entries = {
            uri.get("name", ""): uri.get("uri", "") for uri in root.iter(f"{{{CATALOG_NS}}}uri")
        }
        self.next: list[Catalog] = []
        for entry in root.iter(f"{{{CATALOG_NS}}}nextCatalog"):
            next_path = (self.path.parent / entry.get("catalog", "")).resolve()
            if next_path not in seen:
                self.next.append(Catalog(next_path, seen))

    def lookup(self, name: str) -> Optional[str]:
        """A local file path or a URL, or None."""
        if name in self.entries:
            location = self.entries[name]
            if "://" in location:
                return location
            return str((self.path.parent / location).resolve())
        for catalog in self.next:
            found = catalog.lookup(name)
            if found is not None:
                return found
        return None


def closure(catalog: Catalog, iri: str, include_external: bool = False) -> Graph:
    """The import closure of ``iri`` as one graph, loaded through ``catalog``.
    Documents at URLs are skipped unless ``include_external`` is set."""
    merged = Graph()
    pending = [iri]
    visited: set[str] = set()
    while pending:
        name = pending.pop()
        if name in visited:
            continue
        visited.add(name)
        location = catalog.lookup(name)
        if location is None:
            raise CatalogError(f"{name} has no catalog entry")
        if "://" in location and not include_external:
            continue
        document = Graph().parse(location)
        merged += document
        for node in document.subjects(RDF.type, OWL.Ontology):
            pending += [str(target) for target in document.objects(node, OWL.imports)]
    return merged


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=str(ROOT), help="repository root (default: repo root)")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("write", help="regenerate every catalog")
    commands.add_parser("check", help="fail on drift, unresolved imports or stale known defects")
    load = commands.add_parser("closure", help="load an import closure and print its triple count")
    load.add_argument("iri")
    load.add_argument("--catalog", help="catalog to resolve through (default: the root catalog)")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()

    if args.command == "write":
        written = write(root)
        print(f"{len(written)} catalog file(s) written" + "".join(f"\n  {w}" for w in written))
        return 0
    if args.command == "check":
        problems, known = check(root)
        for line in known:
            print(f"KNOWN {line}")
        for line in problems:
            print(f"PROBLEM {line}", file=sys.stderr)
        if problems:
            return 1
        print(f"ontology catalog consistent, {len(known)} known defect(s) reported")
        return 0
    catalog = Catalog(Path(args.catalog) if args.catalog else root / ONTOLOGY_ROOT / CATALOG_NAME)
    graph = closure(catalog, args.iri)
    print(f"{len(graph)} triples in the import closure of {args.iri}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
