#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Generate the pinned Unicode tables for the LATTICE minting libraries.

Reads the Unicode Character Database files of one version (16.0.0) and
writes the same set of plain-text tables into both libraries, so the Java
and Python minters share their data byte for byte (ADR-A84 point 4,
identity-minting-specification.md §3):

  assigned.txt        ranges of code points assigned in this version
  white_space.txt     ranges with the White_Space property (PropList.txt)
  nfkc_cf.txt         the NFKC_Casefold mapping (DerivedNormalizationProps.txt)
  upper.txt           full uppercase mappings that differ from the code point
  lower.txt           full lowercase mappings that differ from the code point
  cased.txt           ranges with the Cased property (for Final_Sigma)
  case_ignorable.txt  ranges with the Case_Ignorable property (for Final_Sigma)
  SOURCES.txt         source file names, URLs and SHA-256 digests

Formats: a range line is "XXXX" or "XXXX..YYYY" (uppercase hex). A mapping
line is "XXXX;" followed by the target code points in hex separated by
spaces, possibly none (an empty mapping deletes the code point); nfkc_cf.txt
may also map a range "XXXX..YYYY;" to nothing. Lines starting with "#" are
comments. Full case mappings take the unconditional entries of
SpecialCasing.txt, otherwise the simple mapping in UnicodeData.txt;
conditional entries (Final_Sigma, language-specific) are excluded, and
Final_Sigma is implemented in code from cased.txt and case_ignorable.txt.

Usage:
  python3 generate_ucd_tables.py [--ucd-dir DIR] [--check]

--ucd-dir  read the source files from DIR instead of downloading them
--check    regenerate in memory and fail if any committed table differs
"""

from __future__ import annotations

import hashlib
import sys
import urllib.request
from pathlib import Path

VERSION = "16.0.0"
BASE_URL = f"https://www.unicode.org/Public/{VERSION}/ucd/"
SOURCES = ["UnicodeData.txt", "SpecialCasing.txt", "DerivedNormalizationProps.txt", "PropList.txt", "DerivedCoreProperties.txt"]
ROOT = Path(__file__).resolve().parents[1]
TARGETS = [
    ROOT / "python" / "src" / "lattice_minting" / "ucd" / VERSION,
    ROOT / "java" / "src" / "main" / "resources" / "org" / "nebularis" / "lattice" / "minting" / "ucd" / VERSION,
]
HEADER = (
    "# SPDX-License-Identifier: MPL-2.0\n"
    f"# Generated by packages/minting/tools/generate_ucd_tables.py from the Unicode Character Database {VERSION}.\n"
    "# Do not edit. Unicode data is used under the Unicode License v3 (https://www.unicode.org/license.txt).\n"
)


def load_sources(ucd_dir: Path | None) -> dict[str, bytes]:
    out = {}
    for name in SOURCES:
        if ucd_dir is not None:
            out[name] = (ucd_dir / name).read_bytes()
        else:
            with urllib.request.urlopen(BASE_URL + name, timeout=60) as r:
                out[name] = r.read()
    first = out["DerivedNormalizationProps.txt"].decode("utf-8").splitlines()[0]
    if VERSION not in first:
        raise SystemExit(f"source files are not Unicode {VERSION}: {first}")
    return out


def lines(data: bytes):
    for raw in data.decode("utf-8").splitlines():
        body = raw.split("#", 1)[0].strip()
        if body:
            yield [f.strip() for f in body.split(";")]


def cp_range(field: str) -> range:
    a, _, b = field.partition("..")
    return range(int(a, 16), int(b or a, 16) + 1)


def to_ranges(cps: set[int]) -> list[str]:
    out, run = [], None
    for cp in sorted(cps):
        if run and cp == run[1] + 1:
            run[1] = cp
        else:
            if run:
                out.append(run)
            run = [cp, cp]
    if run:
        out.append(run)
    return [f"{a:04X}" if a == b else f"{a:04X}..{b:04X}" for a, b in out]


def prop_set(data: bytes, prop: str) -> set[int]:
    s: set[int] = set()
    for f in lines(data):
        if len(f) >= 2 and f[1] == prop:
            s.update(cp_range(f[0]))
    return s


def build(src: dict[str, bytes]) -> dict[str, str]:
    assigned: set[int] = set()
    simple_upper: dict[int, int] = {}
    simple_lower: dict[int, int] = {}
    pending_first = None
    for f in lines(src["UnicodeData.txt"]):
        cp, name = int(f[0], 16), f[1]
        if name.endswith(", First>"):
            pending_first = cp
            continue
        if name.endswith(", Last>"):
            assigned.update(range(pending_first, cp + 1))
            pending_first = None
            continue
        assigned.add(cp)
        if f[12]:
            simple_upper[cp] = int(f[12], 16)
        if f[13]:
            simple_lower[cp] = int(f[13], 16)

    special_upper: dict[int, list[int]] = {}
    special_lower: dict[int, list[int]] = {}
    for f in lines(src["SpecialCasing.txt"]):
        # code; lower; title; upper; [conditions;]
        if len(f) > 4 and f[4]:
            continue  # conditional: Final_Sigma in code, language-specific excluded
        cp = int(f[0], 16)
        special_lower[cp] = [int(x, 16) for x in f[1].split()]
        special_upper[cp] = [int(x, 16) for x in f[3].split()]

    def mapping(special, simple):
        out = []
        for cp in sorted(assigned):
            target = special.get(cp) or ([simple[cp]] if cp in simple else [cp])
            if target != [cp]:
                out.append(f"{cp:04X};" + " ".join(f"{t:04X}" for t in target))
        return out

    nfkc_cf = []
    for f in lines(src["DerivedNormalizationProps.txt"]):
        if len(f) >= 2 and f[1] == "NFKC_CF":
            target = f[2] if len(f) > 2 else ""
            nfkc_cf.append(f"{f[0].upper()};{target.upper()}")

    tables = {
        "assigned.txt": to_ranges(assigned),
        "white_space.txt": to_ranges(prop_set(src["PropList.txt"], "White_Space")),
        "nfkc_cf.txt": nfkc_cf,
        "upper.txt": mapping(special_upper, simple_upper),
        "lower.txt": mapping(special_lower, simple_lower),
        "cased.txt": to_ranges(prop_set(src["DerivedCoreProperties.txt"], "Cased")),
        "case_ignorable.txt": to_ranges(prop_set(src["DerivedCoreProperties.txt"], "Case_Ignorable")),
    }
    out = {name: HEADER + "\n".join(body) + "\n" for name, body in tables.items()}
    out["SOURCES.txt"] = HEADER + "".join(
        f"{name};{BASE_URL}{name};sha256:{hashlib.sha256(src[name]).hexdigest()}\n" for name in SOURCES)
    return out


def main(argv: list[str]) -> int:
    ucd_dir = None
    check = False
    args = iter(argv)
    for a in args:
        if a == "--ucd-dir":
            ucd_dir = Path(next(args))
        elif a == "--check":
            check = True
        else:
            raise SystemExit(f"unknown argument {a}")
    tables = build(load_sources(ucd_dir))
    stale = []
    for target in TARGETS:
        for name, text in tables.items():
            path = target / name
            if check:
                if not path.exists() or path.read_text(encoding="utf-8") != text:
                    stale.append(str(path))
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    if check:
        for s in stale:
            print("STALE", s)
        print(f"{len(tables) * len(TARGETS) - len(stale)} tables current, {len(stale)} stale")
        return 1 if stale else 0
    print(f"wrote {len(tables)} tables into {len(TARGETS)} libraries")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
